### ISSUE TITLE
Eliminare le categorie dai post

### ISSUE THREAD

**Issue by ariutti** [Openlabs-aps/openlabs-aps.github.io#1]
Individuare un sistema alternativo per eventuale futura classificazione rapida dei post: **tag**.
Il problema con le categorie è che vengono utilizzate per compilare l'URL del post e in casi di categorie multiple (es. `mail, client, linux, unix, mutt`) l'URL si trasforma in qualcosa come:

`https://openlabs-aps.github.io/mail client, linux, unix, mutt/2015/11/04/mutt.html`

il che non è bello!

**Comment by v1a1l1e1** [comment]
Questo sembra un buono spunto:
https://christianspecht.de/2014/10/25/separate-pages-per-tag-category-with-jekyll-without-plugins/
(recuperato da https://stackoverflow.com/questions/1408824/an-easy-way-to-support-tags-in-a-jekyll-blog)

**Comment by ariutti** [comment]
catagorie eliminate: convertite in **tags**. Adesso occorre capire come sfruttare eventualmente i tag come strumento per un accesso rapido agli articoli.
